Repository nextcloud/end_to_end_encryption, pull requests merged in 2020-08, with the labels that each got.

#178 Fix an issue of PropFindPlugin being called too early.
  appinfo/info.xml
  lib/Connector/Sabre/PropFindPlugin.php
  tests/Unit/Connector/Sabre/PropFindPluginTest.php
  tests/Unit/Controller/KeyControllerTest.php
Labels: 3. to review, backport-request

#175 Fix error unlocking a folder when previously deleting the metadata file
  lib/Controller/LockingController.php
  lib/Controller/MetaDataController.php
  lib/MetaDataStorage.php
  tests/Unit/Controller/LockingControllerTest.php
  tests/Unit/Controller/MetaDataControllerTest.php
  tests/Unit/MetaDataStorageTest.php
Labels: 3. to review, backport-request

#183 [stable19] Automatically move legacy metadata files
  lib/MetaDataStorage.php
  tests/Unit/MetaDataStorageTest.php
Labels: 3. to review

#179 Automatically move legacy metadata files
  lib/MetaDataStorage.php
  tests/Unit/MetaDataStorageTest.php
Labels: 3. to review

#184 Bump version to 1.5.2
  Makefile
  appinfo/info.xml
Labels: 2. developing

#185 Bump version to 1.6.1
  Makefile
Labels: 2. developing

#188 Update info.xml - no longer alpha
  appinfo/info.xml
Labels: backport-request

#193 Update minimum client versions
  lib/UserAgentManager.php
Labels: 3. to review, backport-request
