Repository nextcloud/end_to_end_encryption, pull requests merged in 2021-04, with the labels that each got.

#232 Check PHP 8.0 compatibility
  .github/workflows/lint.yml
  .github/workflows/phpunit.yml
  .scrutinizer.yml
  composer.json
  composer.lock
  lib/Connector/Sabre/RedirectRequestPlugin.php
  lib/Db/LockMapper.php
  lib/MetaDataStorage.php
  lib/RollbackService.php
  tests/Unit/EncryptionManagerTest.php
Labels: 2. developing, backport-request, technical debt

#227 Move codecov to action
  .github/workflows/phpunit.yml
Labels: 3. to review

#234 [stable21] Check PHP 8.0 compatibility
  .github/workflows/lint.yml
  .github/workflows/phpunit.yml
  .scrutinizer.yml
  composer.json
  composer.lock
  lib/Connector/Sabre/RedirectRequestPlugin.php
  lib/Db/LockMapper.php
  lib/MetaDataStorage.php
  lib/RollbackService.php
  tests/Unit/EncryptionManagerTest.php
Labels: 3. to review, technical debt

#235 Adjust packaging list
  Makefile
Labels: 3. to review, backport-request
