Repository nextcloud/end_to_end_encryption, pull requests merged in 2022-12, with the labels that each got.

#368 Release 1.11.0
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#356 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#350 Updating psalm.yml workflow from template
  .github/workflows/psalm.yml
Labels: dependencies

#346 Updating lint-php-cs.yml workflow from template
  .github/workflows/lint-php-cs.yml
Labels: dependencies

#345 Updating lint-php.yml workflow from template
  .github/workflows/lint-php.yml
Labels: dependencies

#347 Updating lint-eslint.yml workflow from template
  .github/workflows/lint-eslint.yml
Labels: dependencies

#348 Updating phpunit-mysql.yml workflow from template
  .github/workflows/phpunit-mysql.yml
Labels: dependencies

#351 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#352 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#373 Simplify code flow in lock code
  lib/LockManager.php
Labels: 3. to review, technical debt

#375 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#371 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
