Repository nextcloud/end_to_end_encryption, pull requests merged in 2022-08, with the labels that each got.

#305 Allow user to delete their keys
  .eslintrc.js
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-stylelint.yml
  appinfo/info.xml
  appinfo/routes.php
  babel.config.js
  lib/Controller/EncryptionController.php
  lib/Controller/KeyController.php
  lib/EncryptionManager.php
  lib/Settings/Personal.php
  package-lock.json
  package.json
  src/components/SecuritySection.vue
  src/settings.js
  stylelint.config.js
  templates/settings.php
  tests/Unit/EncryptionManagerTest.php
  webpack.js
Labels: 3. to review

#313 Update npm and node engines versions
  package.json
Labels: dependencies

#311 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#316 Cache end to end encrypted paths
  composer.json
  composer.lock
  lib/Connector/Sabre/APlugin.php
  lib/Connector/Sabre/LockPlugin.php
  lib/Connector/Sabre/PropFindPlugin.php
  lib/Connector/Sabre/RedirectRequestPlugin.php
  lib/E2EEnabledPathCache.php
  tests/Unit/Connector/Sabre/LockPluginTest.php
  tests/Unit/Connector/Sabre/PropFindPluginTest.php
  tests/Unit/Connector/Sabre/RedirectRequestPluginTest.php
  tests/stub.phpstub
Labels: 3. to review

#317 Fix mkcol
  lib/E2EEnabledPathCache.php
Labels: 3. to review

#319 Fix unit test deprecation
  tests/Unit/BackgroundJob/RollbackBackgroundJobTest.php
  tests/Unit/Connector/Sabre/LockPluginTest.php
  tests/Unit/Connector/Sabre/RedirectRequestPluginTest.php
  tests/Unit/EncryptionManagerTest.php
  tests/Unit/KeyStorageTest.php
  tests/Unit/LockManagerTest.php
  tests/Unit/MetaDataStorageTest.php
  tests/Unit/RollbackServiceTest.php
Labels: 3. to review, technical debt

#318 [stable 24] Cache if path is end to end enabled
  lib/Connector/Sabre/APlugin.php
  lib/Connector/Sabre/LockPlugin.php
  lib/Connector/Sabre/PropFindPlugin.php
  lib/Connector/Sabre/RedirectRequestPlugin.php
  lib/E2EEnabledPathCache.php
  tests/Unit/Connector/Sabre/LockPluginTest.php
  tests/Unit/Connector/Sabre/PropFindPluginTest.php
  tests/Unit/Connector/Sabre/RedirectRequestPluginTest.php
  tests/stub.phpstub
Labels: 3. to review
