Repository nextcloud/end_to_end_encryption, pull requests merged in 2023-04, with the labels that each got.

#416 v1.10.2
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#418 v1.12.4
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#419 v1.11.3
  .nextcloudignore
  appinfo/info.xml
  krankerl.toml
  package-lock.json
  package.json
Labels: 3. to review

#378 [stable23] Update nextcloud/ocp dependency
  .github/workflows/phpunit.yml
  composer.lock
Labels: 4. to release, dependencies

#426 docs: fix url for api.md
  doc/api-usage.md
Labels: 3. to review, technical debt
