Repository nextcloud/end_to_end_encryption, pull requests merged in 2023-11, with the labels that each got.

#507 [stable27] Fix npm audit
  js/end_to_end_encryption-adminSettings.js
  js/end_to_end_encryption-adminSettings.js.map
  js/end_to_end_encryption-filedrop.js
  js/end_to_end_encryption-filedrop.js.map
  js/end_to_end_encryption-settings.js
  js/end_to_end_encryption-settings.js.map
  package-lock.json
Labels: 3. to review, dependencies, feedback-requested

#500 [stable25] Fix npm audit
  js/end_to_end_encryption-adminSettings.js
  js/end_to_end_encryption-adminSettings.js.map
  js/end_to_end_encryption-settings.js
  js/end_to_end_encryption-settings.js.LICENSE.txt
  js/end_to_end_encryption-settings.js.map
  package-lock.json
Labels: 3. to review, dependencies, feedback-requested

#499 [stable26] Fix npm audit
  js/end_to_end_encryption-adminSettings.js
  js/end_to_end_encryption-adminSettings.js.map
  js/end_to_end_encryption-filedrop.js
  js/end_to_end_encryption-filedrop.js.map
  js/end_to_end_encryption-settings.js
  js/end_to_end_encryption-settings.js.map
  package-lock.json
Labels: 3. to review, dependencies, feedback-requested

#502 [stable24] Fix npm audit
  js/end_to_end_encryption-adminSettings.js
  js/end_to_end_encryption-adminSettings.js.map
  js/end_to_end_encryption-settings.js
  js/end_to_end_encryption-settings.js.LICENSE.txt
  js/end_to_end_encryption-settings.js.map
  package-lock.json
Labels: 3. to review, dependencies, feedback-requested

#493 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies, feedback-requested

#505 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies, feedback-requested

#516 Fix psalm errors
  composer.json
  composer.lock
  lib/Listener/UserDeletedListener.php
Labels: 2. developing

#517 v1.11.5
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#518 v1.12.6
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review
