Repository nextcloud/end_to_end_encryption, pull requests merged in 2023-05, with the labels that each got.

#425 fix: Call to a member function getUser() on null
  lib/RollbackService.php
Labels: 3. to review

#428 Delete locks for nodes in trashbin
  lib/RollbackService.php
  tests/Unit/RollbackServiceTest.php
Labels: 3. to review, bug

#377 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#381 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#402 [stable26] Update nextcloud/ocp dependency
  composer.json
  composer.lock
Labels: 3. to review, dependencies

#436 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#442 v1.13.1-beta.1
  CHANGELOG.md
  appinfo/info.xml
  lib/Capabilities.php
  tests/Unit/CapabilitiesTest.php
Labels: 3. to review

#441 Add npm-audit-fix workflow
  .github/workflows/npm-audit-fix.yml
Labels: 3. to review, dependencies

#449 [stable27] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#445 [stable25] Fix npm audit
  js/end_to_end_encryption-adminSettings.js
  js/end_to_end_encryption-adminSettings.js.LICENSE.txt
  js/end_to_end_encryption-adminSettings.js.map
  js/end_to_end_encryption-settings.js
  js/end_to_end_encryption-settings.js.LICENSE.txt
  js/end_to_end_encryption-settings.js.map
  package-lock.json
Labels: 3. to review, dependencies

#443 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#447 [stable24] Fix npm audit
  js/end_to_end_encryption-adminSettings.js
  js/end_to_end_encryption-adminSettings.js.LICENSE.txt
  js/end_to_end_encryption-adminSettings.js.map
  js/end_to_end_encryption-settings.js
  js/end_to_end_encryption-settings.js.LICENSE.txt
  js/end_to_end_encryption-settings.js.map
  package-lock.json
Labels: 3. to review, dependencies

#452 v1.11.4
  package-lock.json
  package.json
Labels: 3. to review

#453 v1.12.5
  package-lock.json
  package.json
Labels: 3. to review

#451 v1.10.3
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review
