Repository nextcloud/end_to_end_encryption, pull requests merged in 2024-01, with the labels that each got.

#532 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#523 [master] Fix npm audit
  js/end_to_end_encryption-adminSettings.js
  js/end_to_end_encryption-adminSettings.js.map
  js/end_to_end_encryption-filedrop.js
  js/end_to_end_encryption-filedrop.js.map
  js/end_to_end_encryption-settings.js
  js/end_to_end_encryption-settings.js.map
Labels: 3. to review, dependencies, feedback-requested

#524 [stable28] Fix npm audit
  js/end_to_end_encryption-adminSettings.js
  js/end_to_end_encryption-adminSettings.js.map
  js/end_to_end_encryption-filedrop.js
  js/end_to_end_encryption-filedrop.js.map
  js/end_to_end_encryption-settings.js
  js/end_to_end_encryption-settings.js.map
  package-lock.json
Labels: 3. to review, dependencies, feedback-requested

#522 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies, feedback-requested

#531 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
  composer.lock
  lib/AppInfo/Application.php
  lib/BackgroundJob/RollbackBackgroundJob.php
  lib/Capabilities.php
  lib/Config.php
  lib/Connector/Sabre/APlugin.php
  lib/Connector/Sabre/LockPlugin.php
  lib/Connector/Sabre/PropFindPlugin.php
  lib/Controller/EncryptionController.php
  lib/Controller/KeyController.php
  lib/Controller/LockingController.php
  lib/Controller/MetaDataController.php
  lib/E2EEPublicShareTemplateProvider.php
  lib/E2EEnabledPathCache.php
  lib/EncryptionManager.php
  lib/KeyStorage.php
  lib/Listener/UserDeletedListener.php
  lib/LockManager.php
  lib/MetaDataStorage.php
  lib/Middleware/CanUseAppMiddleware.php
  lib/Middleware/UserAgentCheckMiddleware.php
  lib/Migration/Version1005Date20200312102456.php
  lib/Migration/Version1005Date20200312161123.php
  lib/RollbackService.php
  lib/Settings/Admin.php
  lib/Settings/Personal.php
  tests/Unit/CapabilitiesTest.php
  tests/Unit/Connector/Sabre/LockPluginTest.php
  tests/Unit/Connector/Sabre/PropFindPluginTest.php
  tests/Unit/Controller/KeyControllerTest.php
  tests/Unit/Controller/LockingControllerTest.php
  tests/Unit/Controller/MetaDataControllerTest.php
  tests/Unit/EncryptionManagerTest.php
  tests/Unit/MetaDataStorageTest.php
  tests/Unit/RollbackServiceTest.php
  tests/Unit/UserAgentManagerTest.php
  tests/stub.phpstub
Labels: 3. to review, dependencies, automated

#538 enh(README) New screenshots, setup/troubleshooting instructions
  README.md
Labels: 3. to review, enhancement

#551 [stable28] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#550 [stable27] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#549 [stable26] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#547 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#543 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#552 Update npm and node engines versions
  package.json
Labels: dependencies

#541 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#556 [master] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#554 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#553 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#558 1.15.0-beta.1
  appinfo/info.xml
Labels: 3. to review

#559 v1.15.0-beta.2
  appinfo/info.xml
Labels: 3. to review
