Repository nextcloud/end_to_end_encryption, pull requests merged in 2024-08, with the labels that each got.

#712 [master] Fix npm audit
  js/end_to_end_encryption-adminSettings.js
  js/end_to_end_encryption-adminSettings.js.map
  package-lock.json
Labels: 3. to review, dependencies

#710 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#700 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#669 add a new API to allow user to upload an existing certificate
  appinfo/routes.php
  lib/Controller/KeyController.php
Labels: 3. to review, enhancement

#702 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#717 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#706 [stable28] Fix npm audit
  js/end_to_end_encryption-adminSettings.js
  js/end_to_end_encryption-adminSettings.js.map
  package-lock.json
Labels: 3. to review, dependencies

#718 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#704 [stable27] Fix npm audit
  js/end_to_end_encryption-adminSettings.js
  js/end_to_end_encryption-adminSettings.js.map
  package-lock.json
Labels: 3. to review, dependencies

#711 [stable29] Fix npm audit
  js/end_to_end_encryption-adminSettings.js
  js/end_to_end_encryption-adminSettings.js.map
  js/end_to_end_encryption-filedrop.js
  js/end_to_end_encryption-filedrop.js.map
  js/end_to_end_encryption-settings.js
  js/end_to_end_encryption-settings.js.map
  package-lock.json
Labels: 3. to review, dependencies

#699 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#733 feat: Own the handling of the is-encrypted DAV property
  lib/Connector/Sabre/PropFindPlugin.php
  tests/Unit/Connector/Sabre/PropFindPluginTest.php
  tests/stub.phpstub
Labels: 3. to review, backport-request, technical debt, php
