Repository nextcloud/end_to_end_encryption, pull requests merged in 2024-02, with the labels that each got.

#563 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#561 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#564 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#565 [stable28] chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#566 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#572 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#574 v1.14.2
  appinfo/info.xml
Labels: 4. to release

#575 v1.14.3-beta.1
  appinfo/info.xml
Labels: 4. to release

#576 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#578 Allow access to more kind of versions from the v1 endpoints
  lib/Middleware/ClientHasCapabilityMiddleware.php
Labels: 3. to review, backport-request, php

#580 1.14.3-beta.2
  appinfo/info.xml
Labels: 4. to release
