Repository nextcloud/end_to_end_encryption, pull requests merged in 2024-06, with the labels that each got.

#657 chore(CI): Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#653 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#650 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#661 [master] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#667 fix(deps): Bump dependencies to match nextcloud/ocp:dev-stable27
  composer.json
  composer.lock
  lib/AppInfo/Application.php
  lib/BackgroundJob/RollbackBackgroundJob.php
  lib/Capabilities.php
  lib/Config.php
  lib/Connector/Sabre/APlugin.php
  lib/Connector/Sabre/LockPlugin.php
  lib/Connector/Sabre/PropFindPlugin.php
  lib/Controller/EncryptionController.php
  lib/Controller/KeyController.php
  lib/Controller/LockingController.php
  lib/Controller/MetaDataController.php
  lib/E2EEPublicShareTemplateProvider.php
  lib/E2EEnabledPathCache.php
  lib/EncryptionManager.php
  lib/Exceptions/FileLockedException.php
  lib/Exceptions/FileNotLockedException.php
  lib/Exceptions/KeyExistsException.php
  lib/Exceptions/MetaDataExistsException.php
  lib/Exceptions/MissingMetaDataException.php
  lib/KeyStorage.php
  lib/LockManager.php
  lib/MetaDataStorage.php
  lib/Middleware/CanUseAppMiddleware.php
  lib/Middleware/UserAgentCheckMiddleware.php
  lib/Migration/Version1005Date20200312102456.php
  lib/Migration/Version1005Date20200312161123.php
  lib/RollbackService.php
  lib/Settings/Admin.php
  lib/Settings/Personal.php
  psalm.xml
  tests/Unit/CapabilitiesTest.php
  tests/Unit/Connector/Sabre/LockPluginTest.php
  tests/Unit/Connector/Sabre/PropFindPluginTest.php
  tests/Unit/Controller/KeyControllerTest.php
  tests/Unit/Controller/LockingControllerTest.php
  tests/Unit/Controller/MetaDataControllerTest.php
  tests/Unit/EncryptionManagerTest.php
  tests/Unit/MetaDataStorageTest.php
  tests/Unit/RollbackServiceTest.php
  tests/Unit/UserAgentManagerTest.php
  tests/stub.phpstub
Labels: 3. to review
