Repository nextcloud/end_to_end_encryption, pull requests merged in 2024-03, with the labels that each got.

#582 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#586 docs(api): Fix formatting problems
  doc/api.md
Labels: 3. to review, bug

#588 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#589 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#590 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#585 v1.14.3
  appinfo/info.xml
Labels: 3. to review

#584 v1.15.0
  appinfo/info.xml
Labels: 3. to review

#592 Add x-e2ee-supported header to api example calls documentation
  doc/api.md
Labels: 3. to review

#601 [stable27] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#600 [stable28] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#599 [stable26] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#596 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#598 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#594 Updating phpunit-mysql.yml workflow from template
  .github/workflows/phpunit-mysql.yml
Labels: dependencies

#593 fix: SSE files being mistaken for E2EE
  lib/E2EEnabledPathCache.php
  lib/EncryptionManager.php
  tests/Unit/Connector/Sabre/LockPluginTest.php
  tests/Unit/EncryptionManagerTest.php
Labels: 4. to release, enhancement, php

#604 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#606 [stable27] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#607 [stable28] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#608 [stable26] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#610 Fix check if version is saved as float
  lib/MetaDataStorage.php
Labels: 4. to release, php

#611 chore: v1.15.1
  appinfo/info.xml
Labels: 3. to review

#613 chore: v1.14.4
  appinfo/info.xml
Labels: 3. to review

#614 Fix check also for metadata version 1
  lib/MetaDataStorage.php
Labels: 4. to release, backport-request, php

#616 chore: v1.14.5
  appinfo/info.xml
Labels: 4. to release

#617 chore: v1.15.2
  appinfo/info.xml
Labels: 4. to release

#626 [stable29] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#625 [stable28] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#624 [stable27] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#623 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
