Repository nextcloud/end_to_end_encryption, pull requests merged in 2024-09, with the labels that each got.

#741 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#743 [stable28] Fix npm audit
  js/end_to_end_encryption-adminSettings.js
  js/end_to_end_encryption-adminSettings.js.LICENSE.txt
  js/end_to_end_encryption-adminSettings.js.map
  js/end_to_end_encryption-filedrop.js
  js/end_to_end_encryption-filedrop.js.LICENSE.txt
  js/end_to_end_encryption-filedrop.js.map
  js/end_to_end_encryption-settings.js
  js/end_to_end_encryption-settings.js.LICENSE.txt
  js/end_to_end_encryption-settings.js.map
  package-lock.json
Labels: 3. to review, dependencies

#742 [stable30] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#744 [stable29] Fix npm audit
  js/end_to_end_encryption-adminSettings.js
  js/end_to_end_encryption-adminSettings.js.LICENSE.txt
  js/end_to_end_encryption-adminSettings.js.map
  js/end_to_end_encryption-filedrop.js
  js/end_to_end_encryption-filedrop.js.LICENSE.txt
  js/end_to_end_encryption-filedrop.js.map
  js/end_to_end_encryption-settings.js
  js/end_to_end_encryption-settings.js.LICENSE.txt
  js/end_to_end_encryption-settings.js.map
  package-lock.json
Labels: 3. to review, dependencies

#740 [master] Update nextcloud/ocp dependency
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  composer.lock
Labels: 3. to review, dependencies

#747 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#749 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#750 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#751 [stable29] fix: Upload to the correct path
  js/end_to_end_encryption-filedrop.js
  js/end_to_end_encryption-filedrop.js.map
  src/services/uploadFile.js
  src/views/FileDrop.vue
Labels: 3. to review, bug, javascript

#762 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#769 chore: Prepare v1.16.0
  appinfo/info.xml
Labels: 3. to review

#767 [stable29] Fix npm audit
  js/end_to_end_encryption-adminSettings.js
  js/end_to_end_encryption-adminSettings.js.LICENSE.txt
  js/end_to_end_encryption-adminSettings.js.map
  js/end_to_end_encryption-filedrop.js
  js/end_to_end_encryption-filedrop.js.LICENSE.txt
  js/end_to_end_encryption-filedrop.js.map
  js/end_to_end_encryption-settings.js
  js/end_to_end_encryption-settings.js.LICENSE.txt
  js/end_to_end_encryption-settings.js.map
  package-lock.json
Labels: 3. to review, dependencies

#765 [stable28] Fix npm audit
  js/end_to_end_encryption-adminSettings.js
  js/end_to_end_encryption-adminSettings.js.LICENSE.txt
  js/end_to_end_encryption-adminSettings.js.map
  js/end_to_end_encryption-filedrop.js
  js/end_to_end_encryption-filedrop.js.LICENSE.txt
  js/end_to_end_encryption-filedrop.js.map
  js/end_to_end_encryption-settings.js
  js/end_to_end_encryption-settings.js.LICENSE.txt
  js/end_to_end_encryption-settings.js.map
  package-lock.json
Labels: 3. to review, dependencies

#763 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#779 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#782 chore: Remove reference to ILogger
  tests/Unit/FileServiceTest.php
  tests/stub.phpstub
Labels: 3. to review, technical debt, php
