Repository nextcloud/end_to_end_encryption, pull requests merged in 2024-12, with the labels that each got.

#781 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#797 [stable28] Fix npm audit
  js/end_to_end_encryption-adminSettings.js
  js/end_to_end_encryption-adminSettings.js.LICENSE.txt
  js/end_to_end_encryption-adminSettings.js.map
  js/end_to_end_encryption-filedrop.js
  js/end_to_end_encryption-filedrop.js.LICENSE.txt
  js/end_to_end_encryption-filedrop.js.map
  js/end_to_end_encryption-settings.js
  js/end_to_end_encryption-settings.js.LICENSE.txt
  js/end_to_end_encryption-settings.js.map
  package-lock.json
Labels: 3. to review, dependencies

#798 [stable29] Fix npm audit
  js/end_to_end_encryption-adminSettings.js
  js/end_to_end_encryption-adminSettings.js.LICENSE.txt
  js/end_to_end_encryption-adminSettings.js.map
  js/end_to_end_encryption-filedrop.js
  js/end_to_end_encryption-filedrop.js.LICENSE.txt
  js/end_to_end_encryption-filedrop.js.map
  js/end_to_end_encryption-settings.js
  js/end_to_end_encryption-settings.js.LICENSE.txt
  js/end_to_end_encryption-settings.js.map
  package-lock.json
Labels: 3. to review, dependencies

#778 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#831 fix: Remove some permissions to e2ee nodes to hide some file actions
  js/end_to_end_encryption-files.mjs
  js/end_to_end_encryption-files.mjs.map
  src/services/webDavProxy.ts
Labels: 3. to review, bug, javascript

#834 feat: Verify metadata key against checksum
  __tests__/consts.spec.ts
  js/end_to_end_encryption-filedrop.mjs.map
  js/end_to_end_encryption-files.mjs
  js/end_to_end_encryption-files.mjs.map
  package.json
  src/models.ts
  src/services/crypto.js
  src/services/crypto.spec.ts
  src/services/crypto.ts
  src/services/metadataUtils.spec.ts
  src/services/metadataUtils.ts
  src/services/privateKeyUtils.ts
  src/services/utils.spec.ts
  src/services/utils.ts
Labels: 3. to review, javascript

#833 chore: Prepare v1.17.0-beta.2
  appinfo/info.xml
Labels: 3. to review

#846 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies
