Repository nextcloud/end_to_end_encryption, pull requests merged in 2024-07, with the labels that each got.

#675 chore: Add CODEOWNER
  .github/CODEOWNERS
Labels: 3. to review

#676 chore: Add dependabot config
  .github/dependabot.yml
Labels: 3. to review

#663 [stable28] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#664 [stable27] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#662 [stable29] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#673 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#692 chore: Prepare v1.16.0-beta.1
  appinfo/info.xml
Labels: 3. to review

#693 [stable28] chore: Compile assets
  js/end_to_end_encryption-adminSettings.js
  js/end_to_end_encryption-adminSettings.js.map
  js/end_to_end_encryption-filedrop.js
  js/end_to_end_encryption-filedrop.js.map
  js/end_to_end_encryption-settings.js
  js/end_to_end_encryption-settings.js.map
Labels: 3. to review, bug

#705 [stable29] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#703 [master] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#701 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
