Repository nextcloud/end_to_end_encryption, pull requests merged in 2025-01, with the labels that each got.

#854 chore: E2EE in browser cleanups
  js/end_to_end_encryption-files.mjs
  js/end_to_end_encryption-files.mjs.map
  src/components/MnemonicPromptDialog.vue
  src/services/metadataUtils.ts
  src/services/privateKeyUtils.ts
  src/services/utils.ts
Labels: 3. to review, bug, javascript

#856 feat: Add js test workflow
  .github/workflows/node-test.yml
  js/end_to_end_encryption-files.mjs
  js/end_to_end_encryption-files.mjs.map
  package-lock.json
  package.json
  src/services/crypto.ts
Labels: 3. to review

#858 fix: Reduce scope of intercepted requested
  js/end_to_end_encryption-files.mjs
  js/end_to_end_encryption-files.mjs.map
  src/services/webDavProxy.ts
Labels: 3. to review, bug, javascript

#859 feat: Validate `keyChecksum` length
  js/end_to_end_encryption-files.mjs
  js/end_to_end_encryption-files.mjs.map
  src/services/metadataUtils.ts
Labels: 3. to review, enhancement, javascript

#855 feat: Support more types of mnemonics
  __tests__/api-mock.ts
  __tests__/consts.spec.ts
  js/end_to_end_encryption-files.mjs
  js/end_to_end_encryption-files.mjs.map
  src/services/api.spec.ts
  src/services/metadataUtils.spec.ts
  src/services/privateKeyUtils.spec.ts
  src/services/privateKeyUtils.ts
  src/services/webDavProxy.spec.ts
Labels: 3. to review, enhancement, javascript

#857 feat: Disable copy and download files actions
  js/end_to_end_encryption-files.mjs
  js/end_to_end_encryption-files.mjs.map
  lib/Connector/Sabre/PropFindPlugin.php
  src/files.ts
  src/services/downloadUnencryptedAction.ts
Labels: 3. to review, enhancement, javascript

#867 feat: Allow loading media as `blob:`
  js/end_to_end_encryption-files.mjs
  js/end_to_end_encryption-files.mjs.map
  lib/AppInfo/Application.php
  lib/Listener/AllowBlobMediaInCSPListener.php
  src/files.ts
  src/services/downloadUnencryptedAction.ts
  src/services/state.ts
  src/services/webDavProxy.ts
Labels: 3. to review, enhancement, javascript, php

#864 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#863 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#868 fix: Remove legacy optimization when checking encryption status
  lib/Connector/Sabre/APlugin.php
  lib/Connector/Sabre/LockPlugin.php
  lib/Connector/Sabre/PropFindPlugin.php
  lib/E2EEnabledPathCache.php
  tests/Unit/Connector/Sabre/LockPluginTest.php
  tests/Unit/Connector/Sabre/PropFindPluginTest.php
  tests/Unit/Connector/Sabre/RedirectRequestPluginTest.php
Labels: 3. to review, technical debt, php, performances

#869 chore: Prepare v1.17.0-beta.3
  appinfo/info.xml
Labels: 3. to review

#873 [stable30] fix: Remove legacy optimization when checking encryption status
  .github/workflows/node-test.yml
  lib/Connector/Sabre/APlugin.php
  lib/Connector/Sabre/LockPlugin.php
  lib/Connector/Sabre/PropFindPlugin.php
  lib/E2EEnabledPathCache.php
  tests/Unit/Connector/Sabre/LockPluginTest.php
  tests/Unit/Connector/Sabre/PropFindPluginTest.php
  tests/Unit/Connector/Sabre/RedirectRequestPluginTest.php
Labels: 3. to review

#874 chore: Prepare v1.16.2
  appinfo/info.xml
Labels: 3. to review

#883 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
