Repository nextcloud/end_to_end_encryption, pull requests merged in 2025-02, with the labels that each got.

#890 chore(CI): Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#889 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#893 fix: Support sha-1 algo for user certificate signature
  js/end_to_end_encryption-files.mjs
  js/end_to_end_encryption-files.mjs.map
  src/services/api.ts
  src/services/crypto.spec.ts
  src/services/crypto.ts
  src/services/security.spec.ts
  src/services/security.ts
  src/services/state.spec.ts
  src/services/state.ts
  src/services/webDavProxy.spec.ts
  src/services/webDavProxy.ts
Labels: 3. to review, backport-request, bug, javascript

#895 [stable31] fix: Support sha-1 algo for user certificate signature
  js/end_to_end_encryption-files.mjs
  js/end_to_end_encryption-files.mjs.map
  src/services/api.ts
  src/services/crypto.spec.ts
  src/services/crypto.ts
  src/services/security.spec.ts
  src/services/security.ts
  src/services/state.spec.ts
  src/services/state.ts
  src/services/webDavProxy.spec.ts
  src/services/webDavProxy.ts
Labels: 3. to review, bug, javascript

#894 chore: Prepare 1.17.0-beta.4
  appinfo/info.xml
Labels: 3. to review

#899 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#896 feat: Add documentation about fetching metadata through WebDAV
  doc/api.md
Labels: 3. to review

#909 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#908 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#912 chore: Bump nextcloud/ocp
  composer.json
  composer.lock
  lib/Db/Lock.php
Labels: 3. to review

#922 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#923 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
