Repository nextcloud/end_to_end_encryption, pull requests merged in 2025-08, with the labels that each got.

#1067 ci: update reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies

#1079 chore: Prepare v1.18.0-beta.1 release
  appinfo/info.xml
Labels: 3. to review

#1063 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1084 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
